spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zentao?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

#  redis:
#    host: 192.168.155.150
#    port: 6379
#    password: 12345678

logging:
  path: /Users/guolei/webserver/template/logs
  level:
    cn.sunguolei.qa.springboot.template: debug
#    org.mybatis: debug
#     调试 javamail
#    com.sun.mail: debug
#    javax.mail: debug